
name: build-release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
        
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"
      - run: |
          git fetch --force --tags

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 16
          cache: pnpm

      - run: cd assets && pnpm i && pnpm build
      - run: go get github.com/rakyll/statik
      - run: statik -src=assets/build -f
          
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --clean --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
